import type { Workspace, WorkspaceMember, Project, Task, TaskComment, ActivityItem, NotificationItem } from '../types';

export const DEMO_WORKSPACE: Workspace = {
  id: 'gdgoc-central-chapter',
  name: 'GDGoC Campus Chapter',
  chapterName: 'GDGOC DEMO',
  institution: 'IET DAVV',
  description: 'Google Developer Groups on Campus chapter managing developer events, workshops, hackathons, and study jams.',
  ownerId: 'user-admin-1',
  createdAt: '2026-08-01T09:00:00Z',
  updatedAt: '2026-10-01T14:30:00Z',
};

export const DEMO_MEMBERS: WorkspaceMember[] = [
  {
    uid: 'user-admin-1',
    workspaceId: 'gdgoc-central-chapter',
    email: 'amit.jha@campus-gdg.org',
    displayName: 'Amit jha',
    role: 'Admin',
    teamTrack: 'Core Team',
    status: 'active',
    joinedAt: '2026-08-01T09:00:00Z',
  },
  {
    uid: 'user-lead-2',
    workspaceId: 'gdgoc-central-chapter',
    email: 'manshika@campus-gdg.org',
    displayName: 'manshika',
    role: 'Lead',
    teamTrack: 'Technical',
    status: 'active',
    joinedAt: '2026-08-05T10:00:00Z',
  },
  {
    uid: 'user-lead-3',
    workspaceId: 'gdgoc-central-chapter',
    email: 'lalit.patel@campus-gdg.org',
    displayName: 'lalit patel',
    role: 'Lead',
    teamTrack: 'Operations',
    status: 'active',
    joinedAt: '2026-08-05T11:00:00Z',
  },
  {
    uid: 'user-member-4',
    workspaceId: 'gdgoc-central-chapter',
    email: 'priya.sharma@campus-gdg.org',
    displayName: 'Priya Sharma',
    role: 'Member',
    teamTrack: 'Design & Media',
    status: 'active',
    joinedAt: '2026-08-10T14:00:00Z',
  },
  {
    uid: 'user-member-5',
    workspaceId: 'gdgoc-central-chapter',
    email: 'muskan@campus-gdg.org',
    displayName: 'muskan',
    role: 'Member',
    teamTrack: 'Outreach & PR',
    status: 'active',
    joinedAt: '2026-08-12T16:00:00Z',
  },
];

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-hackathon-2026',
    workspaceId: 'gdgoc-central-chapter',
    name: 'Hackathon 2026: Solutions for Campus',
    description: '36-hour flagship annual student hackathon focused on Google Cloud and Android AI solutions.',
    category: 'Hackathon',
    status: 'active',
    startDate: '2026-10-01',
    endDate: '2026-10-25',
    leadIds: ['user-lead-2'],
    createdBy: 'user-admin-1',
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-10-05T12:00:00Z',
  },
  {
    id: 'proj-cloud-jam',
    workspaceId: 'gdgoc-central-chapter',
    name: 'Cloud Study Jam: GenAI & Gemini',
    description: '4-week study tracks with hands-on labs on Google Cloud Skills Boost.',
    category: 'Study Jam',
    status: 'active',
    startDate: '2026-10-10',
    endDate: '2026-11-05',
    leadIds: ['user-lead-2'],
    createdBy: 'user-lead-2',
    createdAt: '2026-09-20T11:00:00Z',
    updatedAt: '2026-10-06T15:00:00Z',
  },
  {
    id: 'proj-web-dev',
    workspaceId: 'gdgoc-central-chapter',
    name: 'Web Dev Workshop: Fullstack React',
    description: 'Hands-on beginner to intermediate workshop building real web applications with modern tools.',
    category: 'Workshop',
    status: 'active',
    startDate: '2026-10-15',
    endDate: '2026-10-18',
    leadIds: ['user-lead-3'],
    createdBy: 'user-admin-1',
    createdAt: '2026-09-25T09:00:00Z',
    updatedAt: '2026-10-07T08:00:00Z',
  },
  {
    id: 'proj-recruitment',
    workspaceId: 'gdgoc-central-chapter',
    name: 'Fall GDGoC Core Team Recruitment',
    description: 'Application screening, technical interviews, and onboarding of new chapter sub-leads.',
    category: 'Internal',
    status: 'active',
    startDate: '2026-09-28',
    endDate: '2026-10-14',
    leadIds: ['user-admin-1', 'user-lead-3'],
    createdBy: 'user-admin-1',
    createdAt: '2026-09-28T08:00:00Z',
    updatedAt: '2026-10-04T18:00:00Z',
  },
  {
    id: 'proj-social-campaign',
    workspaceId: 'gdgoc-central-chapter',
    name: 'Tech Month Social Media Campaign',
    description: 'Instagram, LinkedIn, and Discord campaigns highlighting student developer projects.',
    category: 'Campaign',
    status: 'planning',
    startDate: '2026-10-20',
    endDate: '2026-11-15',
    leadIds: ['user-member-5'],
    createdBy: 'user-lead-3',
    createdAt: '2026-10-02T14:00:00Z',
    updatedAt: '2026-10-06T11:00:00Z',
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: 'task-1',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-hackathon-2026',
    title: 'Design the hackathon poster & promotional banners',
    description: 'Create high-res SVG and PNG assets for campus notice boards, Instagram posts, and Discord announcement.',
    status: 'Completed',
    priority: 'High',
    category: 'Design',
    assigneeIds: ['user-member-4'],
    dueDate: '2026-10-04',
    completedAt: '2026-10-04T17:00:00Z',
    createdBy: 'user-lead-2',
    createdAt: '2026-09-26T10:00:00Z',
    updatedAt: '2026-10-04T17:00:00Z',
  },
  {
    id: 'task-2',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-hackathon-2026',
    title: 'Build the hackathon registration & team portal',
    description: 'Deploy online portal with team formation support and RSVP confirmation via email.',
    status: 'In Progress',
    priority: 'Urgent',
    category: 'Technical',
    assigneeIds: ['user-lead-2', 'user-member-4'],
    dueDate: '2026-10-10',
    createdBy: 'user-admin-1',
    createdAt: '2026-09-27T11:00:00Z',
    updatedAt: '2026-10-07T14:00:00Z',
  },
  {
    id: 'task-3',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-hackathon-2026',
    title: 'Confirm keynote speaker & mentor roster',
    description: 'Reach out to Google Developer Experts (GDEs) and alumni engineers to confirm judging slots.',
    status: 'In Review',
    priority: 'High',
    category: 'Outreach',
    assigneeIds: ['user-admin-1'],
    dueDate: '2026-10-12',
    createdBy: 'user-admin-1',
    createdAt: '2026-09-28T12:00:00Z',
    updatedAt: '2026-10-07T16:00:00Z',
  },
  {
    id: 'task-4',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-hackathon-2026',
    title: 'Finalize auditorium & high-speed Wi-Fi logistics',
    description: 'Coordinate with university IT department for guest network credentials and power strips.',
    status: 'To Do',
    priority: 'High',
    category: 'Operations',
    assigneeIds: ['user-lead-3'],
    dueDate: '2026-10-14',
    createdBy: 'user-lead-3',
    createdAt: '2026-10-01T09:00:00Z',
    updatedAt: '2026-10-01T09:00:00Z',
  },
  {
    id: 'task-5',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-cloud-jam',
    title: 'Prepare Google Cloud Skills Boost lab track codes',
    description: 'Distribute lab quest vouchers to registered attendees and set up tracking leaderboard spreadsheet.',
    status: 'In Progress',
    priority: 'Medium',
    category: 'Technical',
    assigneeIds: ['user-lead-2'],
    dueDate: '2026-10-09',
    createdBy: 'user-lead-2',
    createdAt: '2026-10-02T10:00:00Z',
    updatedAt: '2026-10-06T19:00:00Z',
  },
  {
    id: 'task-6',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-cloud-jam',
    title: 'Host Cloud Study Jam orientation livestream',
    description: 'Live walkthrough of Cloud console fundamentals and introductory Vertex AI lab overview.',
    status: 'To Do',
    priority: 'Medium',
    category: 'Operations',
    assigneeIds: ['user-lead-2', 'user-member-5'],
    dueDate: '2026-10-11',
    createdBy: 'user-lead-2',
    createdAt: '2026-10-03T11:00:00Z',
    updatedAt: '2026-10-03T11:00:00Z',
  },
  {
    id: 'task-7',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-web-dev',
    title: 'Prepare fullstack workshop slides and starter repository',
    description: 'Create GitHub starter repo with boilerplate Vite, Tailwind, and step-by-step branch checkpoints.',
    status: 'In Review',
    priority: 'Urgent',
    category: 'Technical',
    assigneeIds: ['user-lead-2'],
    dueDate: '2026-10-08',
    createdBy: 'user-admin-1',
    createdAt: '2026-10-02T13:00:00Z',
    updatedAt: '2026-10-08T09:00:00Z',
  },
  {
    id: 'task-8',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-web-dev',
    title: 'Book engineering lab hall & projector test',
    description: 'Verify HDMI connectivity, microphone audio check, and reserve 60 seats with power outlets.',
    status: 'Completed',
    priority: 'Medium',
    category: 'Operations',
    assigneeIds: ['user-lead-3'],
    dueDate: '2026-10-06',
    completedAt: '2026-10-06T15:30:00Z',
    createdBy: 'user-lead-3',
    createdAt: '2026-09-30T14:00:00Z',
    updatedAt: '2026-10-06T15:30:00Z',
  },
  {
    id: 'task-9',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-recruitment',
    title: 'Review 85 incoming member recruitment applications',
    description: 'Score applicant coding challenge repos and design portfolios against standard rubrics.',
    status: 'In Progress',
    priority: 'High',
    category: 'Operations',
    assigneeIds: ['user-admin-1', 'user-lead-3'],
    dueDate: '2026-10-07', // Due yesterday / overdue flag check
    createdBy: 'user-admin-1',
    createdAt: '2026-10-01T15:00:00Z',
    updatedAt: '2026-10-07T11:00:00Z',
  },
  {
    id: 'task-10',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-recruitment',
    title: 'Send interview shortlist invitations via Cal.com',
    description: 'Coordinate 20-minute conversational technical interview slots with top 30 candidates.',
    status: 'To Do',
    priority: 'Medium',
    category: 'Operations',
    assigneeIds: ['user-admin-1'],
    dueDate: '2026-10-13',
    createdBy: 'user-admin-1',
    createdAt: '2026-10-04T10:00:00Z',
    updatedAt: '2026-10-04T10:00:00Z',
  },
  {
    id: 'task-11',
    workspaceId: 'gdgoc-central-chapter',
    projectId: 'proj-social-campaign',
    title: 'Write copywriting copy for Instagram carousel series',
    description: '5-part educational carousel on "What is GDG on Campus and How to Submit a Solution Challenge".',
    status: 'To Do',
    priority: 'Low',
    category: 'Design',
    assigneeIds: ['user-member-5'],
    dueDate: '2026-10-18',
    createdBy: 'user-lead-3',
    createdAt: '2026-10-05T16:00:00Z',
    updatedAt: '2026-10-05T16:00:00Z',
  },
  {
    id: 'task-12',
    workspaceId: 'gdgoc-central-chapter',
    title: 'Audit campus chapter GitHub organization permissions',
    description: 'Ensure 2FA enforcement is enabled for all maintainers and archive abandoned repos from 2025.',
    status: 'Completed',
    priority: 'Low',
    category: 'Technical',
    assigneeIds: ['user-admin-1'],
    dueDate: '2026-10-02',
    completedAt: '2026-10-02T18:00:00Z',
    createdBy: 'user-admin-1',
    createdAt: '2026-09-25T14:00:00Z',
    updatedAt: '2026-10-02T18:00:00Z',
  },
];

export const DEMO_COMMENTS: TaskComment[] = [
  {
    id: 'c-1',
    taskId: 'task-2',
    authorId: 'user-member-4',
    authorName: 'Priya Sharma',
    authorRole: 'Member',
    content: 'Drafted the Figma design for the team formation modal. Added Google fonts and campus brand guidelines.',
    createdAt: '2026-10-05T14:20:00Z',
  },
  {
    id: 'c-2',
    taskId: 'task-2',
    authorId: 'user-lead-2',
    authorName: 'manshika',
    authorRole: 'Lead',
    content: 'Looks awesome Priya! Connecting the registration form to Cloud Firestore now. Will have staging URL ready by tomorrow.',
    createdAt: '2026-10-06T10:15:00Z',
  },
  {
    id: 'c-3',
    taskId: 'task-7',
    authorId: 'user-admin-1',
    authorName: 'Amit jha',
    authorRole: 'Admin',
    content: 'Please double-check slide 14 on Firebase auth tokens to make sure we show modern best practices without client secrets.',
    createdAt: '2026-10-07T11:45:00Z',
  },
];

export const DEMO_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    workspaceId: 'gdgoc-central-chapter',
    actorId: 'user-lead-2',
    actorName: 'manshika',
    actorRole: 'Lead',
    action: 'status_changed',
    targetType: 'task',
    targetId: 'task-7',
    targetTitle: 'Prepare fullstack workshop slides and starter repository',
    details: 'Moved from In Progress to In Review',
    createdAt: '2026-10-08T09:00:00Z',
  },
  {
    id: 'act-2',
    workspaceId: 'gdgoc-central-chapter',
    actorId: 'user-admin-1',
    actorName: 'Amit jha',
    actorRole: 'Admin',
    action: 'commented',
    targetType: 'task',
    targetId: 'task-7',
    targetTitle: 'Prepare fullstack workshop slides and starter repository',
    details: 'Added a review note regarding authentication security',
    createdAt: '2026-10-07T11:45:00Z',
  },
  {
    id: 'act-3',
    workspaceId: 'gdgoc-central-chapter',
    actorId: 'user-lead-3',
    actorName: 'lalit patel',
    actorRole: 'Lead',
    action: 'completed',
    targetType: 'task',
    targetId: 'task-8',
    targetTitle: 'Book engineering lab hall & projector test',
    details: 'Marked task as completed',
    createdAt: '2026-10-06T15:30:00Z',
  },
  {
    id: 'act-4',
    workspaceId: 'gdgoc-central-chapter',
    actorId: 'user-member-4',
    actorName: 'Priya Sharma',
    actorRole: 'Member',
    action: 'completed',
    targetType: 'task',
    targetId: 'task-1',
    targetTitle: 'Design the hackathon poster & promotional banners',
    details: 'Uploaded all finalized banner assets',
    createdAt: '2026-10-04T17:00:00Z',
  },
  {
    id: 'act-5',
    workspaceId: 'gdgoc-central-chapter',
    actorId: 'user-admin-1',
    actorName: 'Amit jha',
    actorRole: 'Admin',
    action: 'created',
    targetType: 'project',
    targetId: 'proj-social-campaign',
    targetTitle: 'Tech Month Social Media Campaign',
    details: 'Created new chapter outreach campaign project',
    createdAt: '2026-10-02T14:00:00Z',
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-admin-1',
    title: 'Review Requested',
    message: 'manshika submitted "Prepare fullstack workshop slides" for review.',
    link: '/tasks?taskId=task-7',
    read: false,
    type: 'review',
    createdAt: '2026-10-08T09:01:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-admin-1',
    title: 'Deadline Overdue Alert',
    message: '"Review 85 incoming member recruitment applications" passed its deadline.',
    link: '/tasks?taskId=task-9',
    read: false,
    type: 'deadline',
    createdAt: '2026-10-08T00:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-admin-1',
    title: 'New Comment',
    message: 'Priya Sharma commented on "Build the hackathon registration & team portal".',
    link: '/tasks?taskId=task-2',
    read: true,
    type: 'comment',
    createdAt: '2026-10-05T14:21:00Z',
  },
];
